### ISSUE TITLE
Tracking issue: Convert ava to mocha in tests

### ISSUE THREAD

**Issue by fhinkel** [google/gts#260]
- [ ] test-clean.ts
- [ ] test-format.ts
- [ ] test-init.ts
- [ ] test-kitchen.ts
- [ ] test-lint.ts
- [ ] test-util.ts

**Comment by vitkarpov** [comment]
@JustinBeckwith @fhinkel guys and gals, why don't you leverage open source community efforts instead of doing this by your own? 😉 I'd be glad to help with that, sees there's no codemod to migrate ava → mocha (only backwards) and it's time to create one.

**Comment by JustinBeckwith** [comment]
Would love help on this one!

**Comment by fhinkel** [comment]
👋 That's so nice of you to offer, @vitkarpov. We welcome outside contributions, but we definitely don't except people to work for us for free.

**Comment by vitkarpov** [comment]
> don't except people to work for us for free.

@fhinkel if "except" were a verb, that sentence would be hilarious 😉Just kidding. I'd like to become a project member in the future, I'd benefit from it a lot, you know, I'm kind of interested in what you guys doing with Node.js in Google, running in the cloud.

**Comment by vitkarpov** [comment]
@fhinkel If I didn't get you right, I'm sorry (genially, nothing's between lines), please, elaborate a little bit on that.

**Comment by fhinkel** [comment]
> > don't except people to work for us for free.
> 
> @fhinkel if "except" were a verb, that sentence would be hilarious 😉

🤣What a typo. I meant expect. We have no expectations that people work for us for free. But if you want to contribute, that's great!

**Comment by vitkarpov** [comment]
Gotcha! I'll wait until https://github.com/google/gts/pull/283/files merge and proceed on other test files.

**Comment by JustinBeckwith** [comment]
So good news! You don't need to wait for that to land.  I did a bunch of the annoying work.  If you're willing - could you work in that branch, and submit a PR against it?

**Comment by vitkarpov** [comment]
> could you work in that branch, and submit a PR against it

Yep, that'd be convenient.

**Comment by vitkarpov** [comment]
I wanted to create a transformation for `jscodeshift` but then understood that it'd be an overengineering for this task, there are not so much test files so it's better to just craft them.

**Comment by vitkarpov** [comment]
Here's a first PR in a series https://github.com/google/gts/pull/291.
